import { v4 as uuidv4 } from 'uuid';
import { IJob, JobStatus, JobType, JobPriority, UserPreferences } from '../types';
import { IProvider } from '../providers/interfaces/IProvider';
import { Router } from '../routing/Router';
import { Job as JobModel } from '../database/models';
import logger from '../utils/logger';
import { AppError, ValidationError } from '../types/errors';
export interface OrchestratorRequest { userId: string; jobType: JobType; input: Record<string, any>; priority?: JobPriority; webhookUrl?: string; userPreferences?: UserPreferences; }
export interface OrchestratorResponse { jobId: string; status: JobStatus; createdAt: Date; }
export class Orchestrator { private router = new Router(); private providers = new Map<string, IProvider>(); registerProvider(provider: IProvider): void { this.providers.set(provider.name.toLowerCase(), provider); } getAvailableProviders(): IProvider[] { return Array.from(this.providers.values()); }
  async createJob(request: OrchestratorRequest): Promise<OrchestratorResponse> { if (!request.userId || !request.jobType || !request.input || !Object.keys(request.input).length) throw new ValidationError('User, job type and input are required'); const providers = this.getAvailableProviders(); if (!providers.length) throw new AppError('NO_PROVIDERS', 'No AI providers are currently available', 503); const decision = await this.router.route(request.jobType, providers); const job = await JobModel.create({ _id: uuidv4(), userId: request.userId, type: request.jobType, status: JobStatus.QUEUED, priority: request.priority || JobPriority.NORMAL, input: request.input, metadata: { requestedAt: new Date(), retryCount: 0, maxRetries: 3, provider: decision.providerName }, webhookUrl: request.webhookUrl }); return { jobId: job.id, status: job.status, createdAt: job.createdAt }; }
  async executeJob(jobId: string): Promise<void> { const job = await JobModel.findById(jobId); if (!job) throw new AppError('JOB_NOT_FOUND', 'Job not found', 404); const provider = this.providers.get(String(job.metadata?.provider || '').toLowerCase()); if (!provider) throw new AppError('PROVIDER_NOT_FOUND', 'Provider not found', 503); job.status = JobStatus.PROCESSING; job.progress = { percentage: 10, stage: 'started' }; await job.save(); try { let output: any; if (job.type === JobType.IMAGE_GENERATION) output = await provider.generateImage(job.input as any); else if (job.type === JobType.VIDEO_GENERATION) output = await provider.generateVideo(job.input as any); else if (job.type === JobType.AUDIO_GENERATION) output = await provider.generateAudio(job.input as any); else if (job.type === JobType.TEXT_TO_SPEECH) output = await provider.synthesizeSpeech(job.input as any); else throw new Error(`Unsupported job type: ${job.type}`); job.status = JobStatus.COMPLETED; job.progress = { percentage: 100, stage: 'completed' }; job.output = output; job.result = { contentUrl: output.url, format: output.format, size: output.size, duration: output.duration, metadata: output.metadata }; job.metadata.completedAt = new Date(); await job.save(); } catch (error) { job.status = (job.metadata.retryCount || 0) < (job.metadata.maxRetries || 3) ? JobStatus.QUEUED : JobStatus.FAILED; job.metadata.retryCount = (job.metadata.retryCount || 0) + 1; job.error = { code: 'EXECUTION_ERROR', message: error instanceof Error ? error.message : 'Unknown error' }; await job.save(); logger.error(`Job execution failed: ${jobId}`, error); } }
  async getJobStatus(jobId: string): Promise<IJob> { const job = await JobModel.findById(jobId); if (!job) throw new AppError('JOB_NOT_FOUND', 'Job not found', 404); return job as IJob; }
  async cancelJob(jobId: string): Promise<void> { const job = await JobModel.findById(jobId); if (!job) throw new AppError('JOB_NOT_FOUND', 'Job not found', 404); if ([JobStatus.COMPLETED, JobStatus.FAILED, JobStatus.CANCELLED].includes(job.status)) throw new AppError('JOB_NOT_CANCELLABLE', 'Job cannot be cancelled', 400); job.status = JobStatus.CANCELLED; await job.save(); }
}
export default new Orchestrator();
