import { Router } from 'express';
import { authenticateToken, AuthenticatedRequest } from '../middleware/auth';
import orchestrator from '../../orchestrator/Orchestrator';
import { validateWithSchema, schemas } from '../../utils/validation';
import { Job } from '../../database/models';
const router = Router();
router.use(authenticateToken);
router.post('/', async (req: AuthenticatedRequest, res, next) => { try { const input = validateWithSchema(req.body, schemas.createJob); const job = await orchestrator.createJob({ userId: req.user!.userId, jobType: input.type as any, input: input.input, priority: input.priority, webhookUrl: input.webhookUrl }); res.status(201).json({ success: true, data: job }); } catch (e) { next(e); } });
router.get('/', async (req: AuthenticatedRequest, res, next) => { try { const jobs = await Job.find({ userId: req.user!.userId }).sort({ createdAt: -1 }).limit(100).lean(); res.json({ success: true, data: jobs }); } catch (e) { next(e); } });
router.get('/:jobId', async (req: AuthenticatedRequest, res, next) => { try { const job = await orchestrator.getJobStatus(req.params.jobId); if (job.userId !== req.user!.userId) return res.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'You do not have access to this job' } }); res.json({ success: true, data: job }); } catch (e) { next(e); } });
router.post('/:jobId/cancel', async (req: AuthenticatedRequest, res, next) => { try { const job = await orchestrator.getJobStatus(req.params.jobId); if (job.userId !== req.user!.userId) return res.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'You do not have access to this job' } }); await orchestrator.cancelJob(req.params.jobId); res.json({ success: true, data: { jobId: req.params.jobId, cancelled: true } }); } catch (e) { next(e); } });
export default router;
