import { Router } from 'express';
import { authenticateToken, AuthenticatedRequest } from '../middleware/auth';
import { Project } from '../../database/models';
import { AppError } from '../../types/errors';
const router = Router();
router.use(authenticateToken);
router.get('/', async (req: AuthenticatedRequest, res, next) => { try { const projects = await Project.find({ userId: req.user!.userId }).sort({ updatedAt: -1 }).lean(); res.json({ success: true, data: projects }); } catch (e) { next(e); } });
router.post('/', async (req: AuthenticatedRequest, res, next) => { try { const { name, type = 'mixed_media', description } = req.body; if (!name) throw new AppError('INVALID_INPUT', 'Project name is required', 400); const project = await Project.create({ userId: req.user!.userId, name, type, description, assets: [], jobs: [], settings: { isPublic: false, allowComments: true, allowSharing: true } }); res.status(201).json({ success: true, data: project }); } catch (e) { next(e); } });
router.get('/:id', async (req: AuthenticatedRequest, res, next) => { try { const project = await Project.findOne({ _id: req.params.id, userId: req.user!.userId }); if (!project) throw new AppError('NOT_FOUND', 'Project not found', 404); res.json({ success: true, data: project }); } catch (e) { next(e); } });
router.patch('/:id', async (req: AuthenticatedRequest, res, next) => { try { const project = await Project.findOneAndUpdate({ _id: req.params.id, userId: req.user!.userId }, { $set: req.body }, { new: true, runValidators: true }); if (!project) throw new AppError('NOT_FOUND', 'Project not found', 404); res.json({ success: true, data: project }); } catch (e) { next(e); } });
export default router;
